---
- name: Install Graphite Software
  hosts: blans65
  become: yes
  become_method: sudo
  gather_facts: true
  tags: [graphite]
  tasks:
          - name: Import EPEL GPG key
            rpm_key:
                    key: http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6
                    state: present
          - name: Add YUM repo
            yum_repository:
                    name: epel
                    description: EPEL YUM repo
                    baseurl: http://dl.fedoraproject.org/pub/epel/$releasever/$basearch
                    gpgcheck: yes
          - name: Update the software package repository
            yum:
                    name: '*'
                    update_cache: yes
          - name: Install Graphite Server
            yum: state=latest name={{ item }}
            with_items:
                    - graphite-web
- name: Install MySQL
  hosts: blans65
  become: yes
  become_method: sudo
  gather_facts: true
  tags: [database]
  tasks:
          - name: Install Database
            yum: state=latest name={{ item }}
            with_items:
                    - mysql
                    - mysql-server
                    - MySQL-python
                    - libselinux-python
          - name: Start mysqld server
            service:
                    name: mysqld
                    state: started
          - wait_for:
                  port: 33062
          - name: create Graphite database user
            mysql_user:
                    name: graphite
                    password: graphite123
                    priv: '*.*:ALL,GRANT'
                    state: present
          - name: Create a databse
            mysql_db:
                    name: graphite
                    state: present

          - name: Update database configuration
            blockinfile:
                    path: /etc/graphite-web/local_settings.py
                    block: DATABASES = { 'default':{ 'NAME':'graphite', 'ENGINE':'django.db.backends.mysql', 'USER':'graphite', 'PASSWORD':'graphite123', } }
          - name: syncdb
            shell: /usr/lib/python2.6/site-packages/graphite/manage.py syncdb --noinput
          - name: Allow Port 80
            shell: iptables -I INPUT -p tcp --dport=80 -m state --state NEW,ESTABLISHED -j ACCEPT
          - name: 
            lineinfile:
                    path: /etc/httpd/conf.d/graphite-web.conf
                    insertafter: '           # Apache 2.2'
                    line: '              Allow from All'
          - name: Start HTTPD server
            service:
                    name: httpd
                    state: started
- name: Install Carbon and Whisper
  hosts: blans65
  become: yes
  become_method: sudo
  gather_facts: true
  tags: [carbon]
  tasks:
          - name: Install carbon and whisper
            yum: state=latest name={{ item }}
            with_items:
                    - python-carbon
                    - python-whisper
          - name: start carbon-cache
            shell: /etc/init.d/carbon-cache start


